#spring:
#  data:
#    mongodb:
#      host: host.docker.internal
#      port: 27017
#      database: user_db
#
#  application:
#    name: user-service
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${eureka_url:http://172.17.0.2:8761/eureka}
#server:
#  port: 3005
#  management:
#    endpoints:
#      web:
#        exposure:
#          include:
#            - "*"
#      endpoint:
#        health:
#          show-details: always